{{- if .Values.secretManagerStore.enabled -}}
{{- range $key, $val := .Values.secretManagerStore.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}-external
  namespace: {{ $.Values.namespace | default "portals" }}
spec:
  refreshInterval: {{ $.Values.refreshInterval }}
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: {{ $key }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        {{ if $.Values.secretManagerStore.buildSecretName -}}
        key: "/{{ $.Values.prefix }}/{{ $.Values.env }}/{{ $val }}"
        {{- else}}
        key: "{{ $val }}"
        {{- end}}
{{- end }}

{{- end}}