{{- if .Values.ssm.enabled -}}
{{- range $key, $params := .Values.ssm.params }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}-store
  namespace: portals
spec:
  refreshInterval: {{ $.Values.refreshInterval }}
  secretStoreRef:
    name: secretstore-awssm
    kind: SecretStore
  target:
    name: {{ $key }}-secret
    creationPolicy: Owner
  data:
    {{- range $paramKey, $paramVal := index $.Values.ssm.params $key }}
    - secretKey: {{ $paramKey }}
      remoteRef:
        key: "/{{ $.Values.prefix }}/{{ $.Values.env }}/{{ $paramVal }}"
    {{- end }}
{{- end }}
{{- end}}
